_BASE_: [
  'centernet_r50_140e_coco.yml'
]

# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
# weights: output/centernet_mbv3_large_140e_coco/model_final
pretrain_weights: null
CenterNet:
  backbone: FasterNet
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

FasterNet:
  return_idx: [0, 2, 4, 6]
  num_classes: 10
  embed_dim: 128
  depths: [1, 2, 8, 2]
  drop_path: 0.0
  act_layer: ReLU

CenterNetDLAFPN:
  first_level: 0
  last_level: 4
  down_ratio: 4
  dcn_v2: False

# MobileNetV3:
#   model_name: large
#   scale: 1.
#   with_extra_blocks: false
#   extra_block_filters: []
#   feature_maps: [4, 7, 13, 16]

TrainReader:
  batch_size: 32
