_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_140e.yml',
  '_base_/centernet_r50.yml',
  '_base_/centernet_reader.yml',
]

save_dir: output/centernet_starnet_10e_coco
pretrain_weights: /paddle/zcd/PaddleClas/convert_pdparams/starnet_s4.pdparams
weights: output/centernet_starnet_10e_coco/model_final

CenterNet:
  backbone: StarNet
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

StarNet:
  base_dim: 32
  depths: [3, 3, 12, 5]

CenterNetDLAFPN:
  first_level: 0
  last_level: 3
  down_ratio: 4
  dcn_v2: False
