_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_140e.yml',
  '_base_/centernet_dla34.yml',
  '_base_/centernet_reader.yml',
]
pretrain_weights: /paddle/zcd/PaddleClas/dla_star_752/best_model.pdparams

DLA:
  depth: 34
  block: StarBasic

weights: output/centernet_dla34_140e_coco/model_final
