_BASE_: [
  'centernet_r50_140e_coco.yml'
]

# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
# weights: output/centernet_mbv3_large_140e_coco/model_final
pretrain_weights: null
CenterNet:
  backbone: FasterNet
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

FasterNet:
  return_idx: [0, 1, 2, 3]
  embed_dim: 64
  depths: [1, 2, 8, 2]
  drop_path: 0.0
  act_layer: GELU

CenterNetDLAFPN:
  first_level: 0
  last_level: 4
  down_ratio: 4
  dcn_v2: False

LearningRate:
    base_lr: 0.001
    schedulers:
    - !PiecewiseDecay
      gamma: 0.1
      milestones: [90, 120]
      use_warmup: False

OptimizerBuilder:
    optimizer:
      type: AdamW
      weight_decay: 0.0001
    regularizer: NULL

TrainReader:
  batch_size: 32
