_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_140e.yml',
  '_base_/centernet_dla34.yml',
  '_base_/centernet_reader.yml',
]
save_dir: output/centernet_dla34_eca_140e_coco
weights: output/centernet_dla34_eca_140e_coco/model_final

CenterNet:
  backbone: DLA
  attention: ECAttentionBlock
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

StarNet:
  base_dim: 32
  depths: [3, 3, 12, 5]

ECAttentionBlock:
  channel_list: [16, 32, 64, 128]

