architecture: FairMOT
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/fairmot_dla34_crowdhuman_pretrained.pdparams
# pretrain_weights: /paddle/zcd/PaddleDetection/output_star_cen_322/best_model/model.pdparams
# pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/DLA34_pretrain.pdparams
for_mot: True

FairMOT:
  detector: CenterNet
  reid: FairMOTEmbeddingHead
  loss: FairMOTLoss
  tracker: JDETracker

# CenterNet:
#   backbone: StarNet
#   neck: CenterNetDLAFPN
#   head: CenterNetHead
#   post_process: CenterNetPostProcess

# StarNet:
#   base_dim: 32
#   depths: [3, 3, 12, 5]

# CenterNetDLAFPN:
#   first_level: 0
#   last_level: 3
#   down_ratio: 4
#   dcn_v2: False

CenterNet:
  backbone: DLA
  neck: CenterNetDLAFPN
  head: CenterNetHead
  post_process: CenterNetPostProcess

CenterNetDLAFPN:
  down_ratio: 4
  last_level: 5
  out_channel: 0
  dcn_v2: True
  with_sge: False

CenterNetHead:
  head_planes: 256
  prior_bias: -2.19
  regress_ltrb: True
  size_loss: 'L1'
  loss_weight: {'heatmap': 1.0, 'size': 0.1, 'offset': 1.0, 'iou': 0.0}
  add_iou: False

FairMOTEmbeddingHead:
  ch_head: 256
  ch_emb: 128

CenterNetPostProcess:
  max_per_img: 500
  down_ratio: 4
  regress_ltrb: True

JDETracker:
  conf_thres: 0.4
  tracked_thresh: 0.4
  metric_type: cosine
  min_box_area: 200
  vertical_ratio: 1.6 # for pedestrian
