_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/optimizer_10e.yml',
  '_base_/fastermot_dla34.yml',
  '_base_/fastermot_reader_576x320.yml',
]

weights: output/fairmot_dla34_30e_576x320/model_final
