_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fastermot_dla34.yml',
  '_base_/fastermot_reader_1088x608.yml',
]

weights: output/fairmot_dla34_30e_1088x608/model_final
