_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_dla34.yml',
  '_base_/ttfnet_reader.yml',
]
weights: output/ttfnet_dla34_1x_coco/model_final
