_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_dla34.yml',
  '_base_/ttfnet_reader.yml',
]

TTFHead:
  hm_loss:
    name: CTFocalLoss
    loss_weight: 1.
  wh_loss: DIouLoss

DIouLoss:
  loss_weight: 5.0
  use_complete_iou_loss: False
  reduction: sum

weights: output/ttfnet_dla34_1x_coco/model_final
