_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_10x.yml',
  '_base_/ttfnet_starnet.yml',
  '_base_/ttfnet_reader.yml',
]
weights: output/ttfnet_darknet53_1x_coco/model_final
