_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fairmot_dla34.yml',
  '_base_/fairmot_reader_1088x608.yml',
]

weights: output/fairmot_dla34_30e_1088x608/model_final
save_dir: output/fairmot_dla34_30e_1088x608_eiou
# pretrain_weights: /paddle/zcd/PaddleClas/dla_star_752/best_model.pdparams

CenterNetHead:
  head_planes: 256
  prior_bias: -2.19
  regress_ltrb: True
  size_loss: 'EIoULoss'
  loss_weight: {'heatmap': 1.0, 'size': 1.0, 'offset': 1.0, 'iou': 0.0}
  add_iou: False
