_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fairmot_dla34.yml',
  '_base_/fairmot_reader_1088x608.yml',
]

weights: output/fairmot_dla34_30e_1088x608/model_final
# save_dir: output/fairmot_dla34_30e_1088x608
# pretrain_weights: /paddle/zcd/PaddleClas/dla_star_752/best_model.pdparams

# DLA:
#   depth: 34
#   block: StarBasic
